services:

  postgres:
    ports:
      - "5432:5432"
    deploy:
      resources: {}

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  elasticsearch:
    ports:
      - "9200:9200"
    deploy:
      resources: {}

  logstash:
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"

  kibana:
    ports:
      - "5601:5601"

  app:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    deploy:
      resources: {}

  prometheus:
    ports:
      - "9090:9090"
    deploy:
      resources: {}

  grafana:
    deploy:
      resources: {}
